### ISSUE TITLE
Erro ao instalar dependências - pyyaml (6.0)

### ISSUE THREAD

**Issue by Ednaxx** [lipe14-ops/brasilapy#19]
Ao executar ` poetry install --with dev`, a instalação do pyyaml (6.0) falha.
No fim do log, aparece isso: "Note: This error originates from the build backend, and is likely not a problem with poetry but with PyYAML (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pyyaml (==6.0)"'."

Apagando o .lock, consigo instalar e executar os testes normalmente.

Problema relacionado: https://github.com/python-poetry/poetry/issues/8287

Rodando no WSL, Ubuntu. 
Python 3.12.7
Poetry recém instalado

## Log completo:

```
Package operations: 31 installs, 1 update, 0 removals

  - Installing pyparsing (3.0.9)
  - Installing attrs (22.1.0)
  - Installing distlib (0.3.6)
  - Installing filelock (3.8.0)
  - Installing iniconfig (1.1.1)
  - Installing packaging (21.3)
  - Installing platformdirs (2.5.2)
  - Installing pluggy (1.0.0)
  - Installing py (1.11.0)
  - Downgrading setuptools (75.1.0 -> 65.4.0): Installing...
  - Downgrading setuptools (75.1.0 -> 65.4.0)
  - Installing tomli (2.0.1)
  - Installing certifi (2022.9.24)
  - Installing cfgv (3.3.1)
  - Installing charset-normalizer (2.1.1)
  - Installing coverage (6.4.4)
  - Installing identify (2.5.5)
  - Installing idna (3.4)
  - Installing mypy-extensions (0.4.3)
  - Installing nodeenv (1.7.0)
  - Installing pytest (7.1.3)
  - Installing pyyaml (6.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  running egg_info
  writing lib/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/root/.local/share/pypoetry/venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
      main()
    File "/root/.local/share/pypoetry/venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 373, in main
      json_out["return_val"] = hook(**hook_input["kwargs"])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/root/.local/share/pypoetry/venv/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 332, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=[])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 302, in _get_build_requires
      self.run_setup()
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/build_meta.py", line 318, in run_setup
      exec(code, locals())
    File "<string>", line 288, in <module>
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/__init__.py", line 117, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 183, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
      dist.run_commands()
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
      self.run_command(cmd)
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/dist.py", line 991, in run_command
      super().run_command(command)
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
      cmd_obj.run()
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 315, in run
      self.find_sources()
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 323, in find_sources
      mm.run()
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 544, in run
      self.add_defaults()
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/command/egg_info.py", line 582, in add_defaults
      sdist.add_defaults(self)
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/command/sdist.py", line 108, in add_defaults
      super().add_defaults()
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 238, in add_defaults
      self._add_defaults_ext()
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/_distutils/command/sdist.py", line 323, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 204, in get_source_files
    File "/tmp/tmpcgjoykqo/.venv/lib/python3.12/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources


  at ~/.local/share/pypoetry/venv/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with PyYAML (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pyyaml (==6.0)"'.

  - Installing toml (0.10.2)
  - Installing types-urllib3 (1.26.25)
  - Installing typing-extensions (4.3.0)
  - Installing urllib3 (1.26.12)
  - Installing virtualenv (20.16.5)
```

**Comment by salarini-e** [comment]
O PyYAML corrigiu isso na versão 6.0.1. Ele já da suporta para builds via PEP 517.
Atualiza aí a dependência para pyyaml = "^6.0.1"
